# Run this example by adding <%= javascript_pack_tag 'hello_coffee' %> to the head of your layout file,
# like app/views/layouts/application.html.erb.

$(document).ready ->
  $('#sidebarCollapse').on 'click', ->
    $('#sidebar').toggleClass 'active'
    return
  return

# ---
# generated by js2coffee 2.2.0
